package gregad.eventmanager.eventcreatorbot.bot.constants;

/**
 * @author Greg Adler
 */
public enum BotStateStep{
    ASK_TITLE,
    ASK_DESCRIPTION,
    ASK_YEAR,
    ASK_MONTH,
    ASK_DAY,
    ASK_HOUR,
    ASK_EVENT_TYPE,
    ASK_TEMPLATE,
    
    EVENT_FORM_VALIDATION,
    EVENT_FORM_CONFIRMATION,
    NO_STATE_STEP,
    
    CHOOSE_EVENT_FILTER,
    SHOW_FILTERED_EVENTS_BY_DATES,
    SHOW_FILTERED_EVENTS_BY_DATES_WAIT,
    MY_EVENTS_BY_TITLE,
    MY_EVENTS_BY_GUEST,
    MY_EVENTS_BY_DATE_FROM_YEAR,
    MY_EVENTS_BY_DATE_FROM_MONTH,
    MY_EVENTS_BY_DATE_FROM_DAY,
    MY_EVENTS_BY_DATE_TO_YEAR,
    MY_EVENTS_BY_DATE_TO_MONTH,
    MY_EVENTS_BY_DATE_TO_DAY,
    MY_FUTURE_EVENTS
}
